Add show_versions helper for debugging
lux-org/lux pull request #450
Opened 2022-01-27 23:02 UTC by cgarciae

## Overview

Adds a `show_versions()` function that prints the lux, pandas, and luxwidget versions. We can ask for this information for debugging.

2022-01-30 18:00 UTC, dorisjlee commented
Could you add instructions in the troubleshooting guide on what the users would have to call to trigger the debug messages?

2022-01-30 18:12 UTC, dorisjlee requested changes

2022-01-30 18:12 UTC, dorisjlee commented on lux/utils/debug_utils.py
> +
```suggestion
import platform

```

2022-01-30 18:12 UTC, dorisjlee commented on lux/utils/debug_utils.py
> +            ("lux", lux.__version__),
```suggestion
            ("python", platform.python_version()),
            ("lux", lux.__version__),
```

2022-01-30 18:12 UTC, dorisjlee commented on lux/utils/debug_utils.py
> +        columns=["Package", "Version"],
```suggestion
        columns=["", "Version"]
```

2022-01-30 18:15 UTC, dorisjlee commented
Note: please edit the PR title so that it is formatted based on the commit guidelines (e.g., DOCS-#...: commit message)

2022-02-03 15:15 UTC, cgarciae commented
Hey @dorisjlee! Sounds good, `lux.debug` could aggregate information from all these functions. Once this are merge that would be easy.

2022-02-03 21:23 UTC, cgarciae commented
@dorisjlee added packages from `jupyter --version`

2022-02-07 20:09 UTC, dorisjlee approved these changes

2022-02-07 20:10 UTC, merged

2022-02-07 20:10 UTC, dorisjlee commented
Looks good! Thanks @cgarciae!